export type Asma = { n: number; ar: string; en: string; meanAr: string; meanEn: string };

export const ASMA: Asma[] = [
  { n: 1, ar: "الرحمن", en: "Ar-Rahman", meanAr: "واسع الرحمة", meanEn: "The Most Merciful" },
  { n: 2, ar: "الرحيم", en: "Ar-Raheem", meanAr: "دائم الرحمة", meanEn: "The Especially Merciful" },
  { n: 3, ar: "الملك", en: "Al-Malik", meanAr: "المالك المتصرف", meanEn: "The King" },
  { n: 4, ar: "القدوس", en: "Al-Quddus", meanAr: "المنزّه عن كل نقص", meanEn: "The Holy" },
  { n: 5, ar: "السلام", en: "As-Salam", meanAr: "مانح السلام", meanEn: "The Source of Peace" },
  { n: 6, ar: "المؤمن", en: "Al-Mu’min", meanAr: "مانح الأمن", meanEn: "The Giver of Faith" },
  { n: 7, ar: "المهيمن", en: "Al-Muhaymin", meanAr: "الرقيب الحافظ", meanEn: "The Guardian" },
  { n: 8, ar: "العزيز", en: "Al-Aziz", meanAr: "الغالب الذي لا يُقهر", meanEn: "The Almighty" },
  { n: 9, ar: "الجبار", en: "Al-Jabbar", meanAr: "جابر الكسر والقاهر", meanEn: "The Compeller" },
  { n: 10, ar: "المتكبر", en: "Al-Mutakabbir", meanAr: "المتعالي عن صفات الخلق", meanEn: "The Supreme" },
  { n: 11, ar: "الخالق", en: "Al-Khaliq", meanAr: "الموجد من العدم", meanEn: "The Creator" },
  { n: 12, ar: "البارئ", en: "Al-Bari’", meanAr: "المصوّر على غير مثال", meanEn: "The Evolver" },
  { n: 13, ar: "المصور", en: "Al-Musawwir", meanAr: "مانح الصور", meanEn: "The Fashioner" },
  { n: 14, ar: "الغفار", en: "Al-Ghaffar", meanAr: "كثير المغفرة", meanEn: "The All-Forgiving" },
  { n: 15, ar: "القهار", en: "Al-Qahhar", meanAr: "الغالب على كل شيء", meanEn: "The Subduer" },
  { n: 16, ar: "الوهاب", en: "Al-Wahhab", meanAr: "كثير العطاء", meanEn: "The Bestower" },
  { n: 17, ar: "الرزاق", en: "Ar-Razzaq", meanAr: "موصل الأرزاق", meanEn: "The Provider" },
  { n: 18, ar: "الفتاح", en: "Al-Fattah", meanAr: "فاتح أبواب الخير", meanEn: "The Opener" },
  { n: 19, ar: "العليم", en: "Al-Alim", meanAr: "العالم بكل شيء", meanEn: "The All-Knowing" },
  { n: 20, ar: "القابض", en: "Al-Qabid", meanAr: "قابض الأرزاق والأرواح", meanEn: "The Withholder" },
  { n: 21, ar: "الباسط", en: "Al-Basit", meanAr: "باسط الرزق والرحمة", meanEn: "The Extender" },
  { n: 22, ar: "الخافض", en: "Al-Khafid", meanAr: "خافض الجبابرة", meanEn: "The Abaser" },
  { n: 23, ar: "الرافع", en: "Ar-Rafi", meanAr: "رافع المؤمنين", meanEn: "The Exalter" },
  { n: 24, ar: "المعز", en: "Al-Mu’izz", meanAr: "مانح العز", meanEn: "The Honourer" },
  { n: 25, ar: "المذل", en: "Al-Mudhill", meanAr: "خافض المتكبرين", meanEn: "The Humbler" },
  { n: 26, ar: "السميع", en: "As-Sami", meanAr: "الذي يسمع كل شيء", meanEn: "The All-Hearing" },
  { n: 27, ar: "البصير", en: "Al-Basir", meanAr: "الذي يرى كل شيء", meanEn: "The All-Seeing" },
  { n: 28, ar: "الحكم", en: "Al-Hakam", meanAr: "القاضي بالحق", meanEn: "The Judge" },
  { n: 29, ar: "العدل", en: "Al-Adl", meanAr: "الكامل العدل", meanEn: "The Just" },
  { n: 30, ar: "اللطيف", en: "Al-Latif", meanAr: "البرّ الرفيق", meanEn: "The Subtle" },
  { n: 31, ar: "الخبير", en: "Al-Khabir", meanAr: "العليم بدقائق الأمور", meanEn: "The All-Aware" },
  { n: 32, ar: "الحليم", en: "Al-Halim", meanAr: "الذي لا يعاجل بالعقوبة", meanEn: "The Forbearing" },
  { n: 33, ar: "العظيم", en: "Al-Azim", meanAr: "ذو العظمة", meanEn: "The Magnificent" },
  { n: 34, ar: "الغفور", en: "Al-Ghafur", meanAr: "واسع المغفرة", meanEn: "The Great Forgiver" },
  { n: 35, ar: "الشكور", en: "Ash-Shakur", meanAr: "الذي يجزي على القليل كثيراً", meanEn: "The Appreciative" },
  { n: 36, ar: "العلي", en: "Al-Ali", meanAr: "رفيع القدر", meanEn: "The Most High" },
  { n: 37, ar: "الكبير", en: "Al-Kabir", meanAr: "الذي كل شيء دونه", meanEn: "The Most Great" },
  { n: 38, ar: "الحفيظ", en: "Al-Hafiz", meanAr: "حافظ الخلق", meanEn: "The Preserver" },
  { n: 39, ar: "المقيت", en: "Al-Muqit", meanAr: "موصل الأقوات", meanEn: "The Nourisher" },
  { n: 40, ar: "الحسيب", en: "Al-Hasib", meanAr: "الكافي والمحاسب", meanEn: "The Reckoner" },
  { n: 41, ar: "الجليل", en: "Al-Jalil", meanAr: "ذو الجلال", meanEn: "The Majestic" },
  { n: 42, ar: "الكريم", en: "Al-Karim", meanAr: "الجواد المعطي", meanEn: "The Generous" },
  { n: 43, ar: "الرقيب", en: "Ar-Raqib", meanAr: "المطلع على كل شيء", meanEn: "The Watchful" },
  { n: 44, ar: "المجيب", en: "Al-Mujib", meanAr: "مجيب الدعاء", meanEn: "The Responsive" },
  { n: 45, ar: "الواسع", en: "Al-Wasi", meanAr: "واسع الفضل والعلم", meanEn: "The All-Encompassing" },
  { n: 46, ar: "الحكيم", en: "Al-Hakim", meanAr: "صاحب الحكمة", meanEn: "The Wise" },
  { n: 47, ar: "الودود", en: "Al-Wadud", meanAr: "المحبّ لأوليائه", meanEn: "The Most Loving" },
  { n: 48, ar: "المجيد", en: "Al-Majid", meanAr: "واسع الكرم", meanEn: "The Glorious" },
  { n: 49, ar: "الباعث", en: "Al-Ba’ith", meanAr: "باعث الخلق بعد الموت", meanEn: "The Resurrector" },
  { n: 50, ar: "الشهيد", en: "Ash-Shahid", meanAr: "الحاضر المطلع", meanEn: "The Witness" },
  { n: 51, ar: "الحق", en: "Al-Haqq", meanAr: "الثابت الذي لا يزول", meanEn: "The Truth" },
  { n: 52, ar: "الوكيل", en: "Al-Wakil", meanAr: "الكافي لمن توكّل عليه", meanEn: "The Trustee" },
  { n: 53, ar: "القوي", en: "Al-Qawi", meanAr: "ذو القوة المتين", meanEn: "The Strong" },
  { n: 54, ar: "المتين", en: "Al-Matin", meanAr: "شديد القوة", meanEn: "The Firm" },
  { n: 55, ar: "الولي", en: "Al-Wali", meanAr: "الناصر المتولي", meanEn: "The Protecting Friend" },
  { n: 56, ar: "الحميد", en: "Al-Hamid", meanAr: "المستحق للحمد", meanEn: "The Praiseworthy" },
  { n: 57, ar: "المحصي", en: "Al-Muhsi", meanAr: "الذي أحصى كل شيء", meanEn: "The Accounter" },
  { n: 58, ar: "المبدئ", en: "Al-Mubdi", meanAr: "منشئ الخلق", meanEn: "The Originator" },
  { n: 59, ar: "المعيد", en: "Al-Mu’id", meanAr: "الذي يعيد الخلق", meanEn: "The Restorer" },
  { n: 60, ar: "المحيي", en: "Al-Muhyi", meanAr: "واهب الحياة", meanEn: "The Giver of Life" },
  { n: 61, ar: "المميت", en: "Al-Mumit", meanAr: "الذي يميت", meanEn: "The Causer of Death" },
  { n: 62, ar: "الحي", en: "Al-Hayy", meanAr: "الدائم الحياة", meanEn: "The Ever-Living" },
  { n: 63, ar: "القيوم", en: "Al-Qayyum", meanAr: "القائم على كل شيء", meanEn: "The Self-Subsisting" },
  { n: 64, ar: "الواجد", en: "Al-Wajid", meanAr: "الذي لا يعوزه شيء", meanEn: "The Finder" },
  { n: 65, ar: "الماجد", en: "Al-Majid", meanAr: "ذو المجد", meanEn: "The Noble" },
  { n: 66, ar: "الواحد", en: "Al-Wahid", meanAr: "المنفرد في ذاته", meanEn: "The One" },
  { n: 67, ar: "الأحد", en: "Al-Ahad", meanAr: "الذي لا مثيل له", meanEn: "The Unique" },
  { n: 68, ar: "الصمد", en: "As-Samad", meanAr: "السيد الذي يُقصد", meanEn: "The Eternal Refuge" },
  { n: 69, ar: "القادر", en: "Al-Qadir", meanAr: "ذو القدرة", meanEn: "The Able" },
  { n: 70, ar: "المقتدر", en: "Al-Muqtadir", meanAr: "بالغ القدرة", meanEn: "The Powerful" },
  { n: 71, ar: "المقدم", en: "Al-Muqaddim", meanAr: "الذي يقدّم من يشاء", meanEn: "The Expediter" },
  { n: 72, ar: "المؤخر", en: "Al-Mu’akhkhir", meanAr: "الذي يؤخّر من يشاء", meanEn: "The Delayer" },
  { n: 73, ar: "الأول", en: "Al-Awwal", meanAr: "الذي ليس قبله شيء", meanEn: "The First" },
  { n: 74, ar: "الآخر", en: "Al-Akhir", meanAr: "الذي ليس بعده شيء", meanEn: "The Last" },
  { n: 75, ar: "الظاهر", en: "Az-Zahir", meanAr: "الظاهر وجوده بالآيات", meanEn: "The Manifest" },
  { n: 76, ar: "الباطن", en: "Al-Batin", meanAr: "المحتجب عن الأبصار", meanEn: "The Hidden" },
  { n: 77, ar: "الوالي", en: "Al-Wali", meanAr: "المالك المتصرف", meanEn: "The Governor" },
  { n: 78, ar: "المتعالي", en: "Al-Muta’ali", meanAr: "المنزّه عن صفات الخلق", meanEn: "The Most Exalted" },
  { n: 79, ar: "البر", en: "Al-Barr", meanAr: "العطوف المحسن", meanEn: "The Source of Goodness" },
  { n: 80, ar: "التواب", en: "At-Tawwab", meanAr: "قابل التوبة", meanEn: "The Accepter of Repentance" },
  { n: 81, ar: "المنتقم", en: "Al-Muntaqim", meanAr: "آخذ حق المظلوم", meanEn: "The Avenger" },
  { n: 82, ar: "العفو", en: "Al-Afuww", meanAr: "ماحي الذنوب", meanEn: "The Pardoner" },
  { n: 83, ar: "الرؤوف", en: "Ar-Ra’uf", meanAr: "شديد الرأفة", meanEn: "The Kind" },
  { n: 84, ar: "مالك الملك", en: "Malik-ul-Mulk", meanAr: "صاحب الملك", meanEn: "Master of Sovereignty" },
  { n: 85, ar: "ذو الجلال والإكرام", en: "Dhul-Jalali wal-Ikram", meanAr: "صاحب الجلال والإكرام", meanEn: "Lord of Majesty and Honour" },
  { n: 86, ar: "المقسط", en: "Al-Muqsit", meanAr: "العادل في حكمه", meanEn: "The Equitable" },
  { n: 87, ar: "الجامع", en: "Al-Jami", meanAr: "جامع الخلق ليوم القيامة", meanEn: "The Gatherer" },
  { n: 88, ar: "الغني", en: "Al-Ghani", meanAr: "المستغني عن الخلق", meanEn: "The Self-Sufficient" },
  { n: 89, ar: "المغني", en: "Al-Mughni", meanAr: "مغني من يشاء", meanEn: "The Enricher" },
  { n: 90, ar: "المانع", en: "Al-Mani", meanAr: "الذي يمنع ما يشاء", meanEn: "The Withholder of Harm" },
  { n: 91, ar: "الضار", en: "Ad-Darr", meanAr: "مقدّر الضر", meanEn: "The Distresser" },
  { n: 92, ar: "النافع", en: "An-Nafi", meanAr: "مقدّر النفع", meanEn: "The Benefactor" },
  { n: 93, ar: "النور", en: "An-Nur", meanAr: "منوّر السموات والأرض", meanEn: "The Light" },
  { n: 94, ar: "الهادي", en: "Al-Hadi", meanAr: "هادي الخلق", meanEn: "The Guide" },
  { n: 95, ar: "البديع", en: "Al-Badi", meanAr: "مبدع الخلق", meanEn: "The Incomparable" },
  { n: 96, ar: "الباقي", en: "Al-Baqi", meanAr: "الدائم بعد فناء الخلق", meanEn: "The Everlasting" },
  { n: 97, ar: "الوارث", en: "Al-Warith", meanAr: "باقي بعد فناء الورّاث", meanEn: "The Inheritor" },
  { n: 98, ar: "الرشيد", en: "Ar-Rashid", meanAr: "الهادي إلى الرشاد", meanEn: "The Guide to Right" },
  { n: 99, ar: "الصبور", en: "As-Sabur", meanAr: "الحليم الذي لا يعاجل", meanEn: "The Patient" },
];

export function asmaOfDay(d = new Date()) {
  const start = new Date(d.getFullYear(), 0, 0).getTime();
  const day = Math.floor((d.getTime() - start) / 86400000);
  return ASMA[day % ASMA.length]!;
}
