export type NameEntry = {
  ar: string;
  en: string;
  gender: "m" | "f" | "u";
  meanAr: string;
  meanEn: string;
};

export const NAMES: NameEntry[] = [
  { ar: "محمد", en: "Muhammad", gender: "m", meanAr: "المحمود كثير الحمد", meanEn: "The praised one" },
  { ar: "عبدالله", en: "Abdullah", gender: "m", meanAr: "عبد الله", meanEn: "Servant of God" },
  { ar: "عبدالرحمن", en: "Abdulrahman", gender: "m", meanAr: "عبد الرحمن", meanEn: "Servant of the Most Merciful" },
  { ar: "عبدالعزيز", en: "Abdulaziz", gender: "m", meanAr: "عبد العزيز", meanEn: "Servant of the Almighty" },
  { ar: "أحمد", en: "Ahmad", gender: "m", meanAr: "أكثر حمداً", meanEn: "Most praiseworthy" },
  { ar: "علي", en: "Ali", gender: "m", meanAr: "الرفيع القدر", meanEn: "The exalted" },
  { ar: "عمر", en: "Omar", gender: "m", meanAr: "العامر الطويل العمر", meanEn: "Long-lived, flourishing" },
  { ar: "عثمان", en: "Othman", gender: "m", meanAr: "فرخ الحبارى — اسم خليفة راشد", meanEn: "A rightly guided caliph’s name" },
  { ar: "حسن", en: "Hassan", gender: "m", meanAr: "الجميل الحسن", meanEn: "Handsome, good" },
  { ar: "حسين", en: "Hussein", gender: "m", meanAr: "تصغير حسن", meanEn: "Little Hassan" },
  { ar: "يوسف", en: "Yusuf", gender: "m", meanAr: "يزيد حسنه — اسم نبي", meanEn: "God increases; a prophet’s name" },
  { ar: "إبراهيم", en: "Ibrahim", gender: "m", meanAr: "أبو الأنبياء", meanEn: "Father of prophets" },
  { ar: "إسماعيل", en: "Ismail", gender: "m", meanAr: "سمع الله — اسم نبي", meanEn: "God has heard" },
  { ar: "يحيى", en: "Yahya", gender: "m", meanAr: "يحيا — اسم نبي", meanEn: "He lives" },
  { ar: "زكريا", en: "Zakariya", gender: "m", meanAr: "يذكر الله", meanEn: "God remembers" },
  { ar: "سليمان", en: "Sulaiman", gender: "m", meanAr: "سالم مسالم", meanEn: "Peaceful" },
  { ar: "داود", en: "Dawud", gender: "m", meanAr: "حبيب — اسم نبي", meanEn: "Beloved; a prophet’s name" },
  { ar: "موسى", en: "Musa", gender: "m", meanAr: "اسم نبي كليم الله", meanEn: "A prophet’s name" },
  { ar: "عيسى", en: "Isa", gender: "m", meanAr: "اسم نبي", meanEn: "A prophet’s name" },
  { ar: "خالد", en: "Khalid", gender: "m", meanAr: "الدائم الباقي", meanEn: "Eternal, immortal" },
  { ar: "فهد", en: "Fahd", gender: "m", meanAr: "الفهد — الشجاعة والسرعة", meanEn: "Cheetah — swift and brave" },
  { ar: "سلطان", en: "Sultan", gender: "m", meanAr: "السلطة والقوة", meanEn: "Authority, power" },
  { ar: "سعود", en: "Saud", gender: "m", meanAr: "السعادة واليمن", meanEn: "Fortune, good luck" },
  { ar: "سلمان", en: "Salman", gender: "m", meanAr: "السالم المحفوظ", meanEn: "Safe, at peace" },
  { ar: "فيصل", en: "Faisal", gender: "m", meanAr: "الفاصل بين الحق والباطل", meanEn: "Decisive, arbiter" },
  { ar: "تركي", en: "Turki", gender: "m", meanAr: "المنسوب إلى الترك / اسم نجدى أصيل", meanEn: "A classic Najdi name" },
  { ar: "نواف", en: "Nawaf", gender: "m", meanAr: "العالي المرتفع", meanEn: "Elevated, lofty" },
  { ar: "مشعل", en: "Mishaal", gender: "m", meanAr: "المصباح المضيء", meanEn: "Torch, light" },
  { ar: "بندر", en: "Bandar", gender: "m", meanAr: "الميناء / السيد", meanEn: "Harbour; a noble" },
  { ar: "ماجد", en: "Majid", gender: "m", meanAr: "ذو المجد", meanEn: "Glorious, noble" },
  { ar: "وليد", en: "Waleed", gender: "m", meanAr: "المولود حديثاً", meanEn: "Newborn" },
  { ar: "سعد", en: "Saad", gender: "m", meanAr: "السعادة واليمن", meanEn: "Happiness, good fortune" },
  { ar: "سعيد", en: "Saeed", gender: "m", meanAr: "السعيد", meanEn: "Happy, fortunate" },
  { ar: "راشد", en: "Rashid", gender: "m", meanAr: "المهتدي الراشد", meanEn: "Rightly guided" },
  { ar: "نايف", en: "Naif", gender: "m", meanAr: "الزائد العالي", meanEn: "Excess, eminent" },
  { ar: "طلال", en: "Talal", gender: "m", meanAr: "الطّل الحسن المنظر", meanEn: "Goodly, admirable" },
  { ar: "حمد", en: "Hamad", gender: "m", meanAr: "الحمد والشكر", meanEn: "Praise" },
  { ar: "حمدان", en: "Hamdan", gender: "m", meanAr: "كثير الحمد", meanEn: "Much praised" },
  { ar: "ياسر", en: "Yasser", gender: "m", meanAr: "الميسّر السهل", meanEn: "Ease, prosperity" },
  { ar: "أنس", en: "Anas", gender: "m", meanAr: "الأنس والمودة", meanEn: "Companionship" },
  { ar: "زيد", en: "Zaid", gender: "m", meanAr: "الزيادة والنماء", meanEn: "Growth, increase" },
  { ar: "حمزة", en: "Hamza", gender: "m", meanAr: "الأسد — الشجاعة", meanEn: "Lion, courage" },
  { ar: "عمران", en: "Omran", gender: "m", meanAr: "العمران والازدهار", meanEn: "Prosperity, building" },
  { ar: "طارق", en: "Tariq", gender: "m", meanAr: "النجم الطارق / الساري ليلاً", meanEn: "Night visitor; the morning star" },
  { ar: "سامي", en: "Sami", gender: "m", meanAr: "العالي الرفيع", meanEn: "Elevated" },
  { ar: "نبيل", en: "Nabil", gender: "m", meanAr: "الشريف النبيل", meanEn: "Noble" },
  { ar: "كريم", en: "Karim", gender: "m", meanAr: "الجواد الكريم", meanEn: "Generous" },
  { ar: "فارس", en: "Fares", gender: "m", meanAr: "الفارس الشجاع", meanEn: "Knight, horseman" },
  { ar: "باسل", en: "Basil", gender: "m", meanAr: "الشجاع الباسل", meanEn: "Brave" },
  { ar: "مشاري", en: "Mishari", gender: "m", meanAr: "من المشاركة والعطاء", meanEn: "Partner, sharer" },
  { ar: "عبدالملك", en: "Abdulmalik", gender: "m", meanAr: "عبد الملك", meanEn: "Servant of the King" },
  { ar: "عبدالإله", en: "Abdulelah", gender: "m", meanAr: "عبد الإله", meanEn: "Servant of God" },
  { ar: "عبداللطيف", en: "Abdullatif", gender: "m", meanAr: "عبد اللطيف", meanEn: "Servant of the Subtle" },
  { ar: "فاطمة", en: "Fatimah", gender: "f", meanAr: "التي فُطمت عن السوء — ابنة النبي", meanEn: "Weaned from ill; the Prophet’s daughter" },
  { ar: "عائشة", en: "Aisha", gender: "f", meanAr: "الحية النابضة — أم المؤمنين", meanEn: "Alive, lively" },
  { ar: "خديجة", en: "Khadijah", gender: "f", meanAr: "المولودة قبل أوانها — أولى أزواج النبي", meanEn: "Premature; the Prophet’s first wife" },
  { ar: "مريم", en: "Maryam", gender: "f", meanAr: "العابدة — اسم أم عيسى", meanEn: "Devout; mother of Jesus" },
  { ar: "نورة", en: "Noura", gender: "f", meanAr: "الضياء والنور", meanEn: "Light, radiance" },
  { ar: "سارة", en: "Sarah", gender: "f", meanAr: "الأميرة / زوجة إبراهيم", meanEn: "Princess; wife of Ibrahim" },
  { ar: "هند", en: "Hind", gender: "f", meanAr: "اسم عربي تليد لجماعة الإبل", meanEn: "A classic Arabian name" },
  { ar: "حصة", en: "Hessa", gender: "f", meanAr: "النصيب والحظ", meanEn: "Share, fortune" },
  { ar: "منيرة", en: "Munirah", gender: "f", meanAr: "المضيئة المنيرة", meanEn: "Luminous" },
  { ar: "الجوهرة", en: "Aljawhara", gender: "f", meanAr: "الجوهرة الثمينة", meanEn: "Jewel" },
  { ar: "جواهر", en: "Jawaher", gender: "f", meanAr: "الجواهر الكريمة", meanEn: "Jewels" },
  { ar: "العنود", en: "Alanoud", gender: "f", meanAr: "الصعبة المنال العزيزة", meanEn: "Rare, hard to attain" },
  { ar: "مشاعل", en: "Mashael", gender: "f", meanAr: "المصابيح المضيئة", meanEn: "Torches, lights" },
  { ar: "جود", en: "Joud", gender: "f", meanAr: "الكرم والجود", meanEn: "Generosity" },
  { ar: "لمى", en: "Lama", gender: "f", meanAr: "سمرة الشفة المحبوبة", meanEn: "A dark-lipped beauty" },
  { ar: "ليان", en: "Layan", gender: "f", meanAr: "اللين والنعومة", meanEn: "Softness, ease" },
  { ar: "رهف", en: "Rahaf", gender: "f", meanAr: "الرقة واللطف", meanEn: "Delicacy, gentleness" },
  { ar: "جنى", en: "Jana", gender: "f", meanAr: "الثمر المجتنى", meanEn: "Harvest, fruit" },
  { ar: "تالا", en: "Tala", gender: "f", meanAr: "النخلة الصغيرة / الإشراق", meanEn: "Young palm; radiance" },
  { ar: "دانة", en: "Dana", gender: "f", meanAr: "اللؤلؤة الكبيرة", meanEn: "A large pearl" },
  { ar: "ريناد", en: "Renad", gender: "f", meanAr: "العود الطيب الرائحة", meanEn: "A sweet-scented tree" },
  { ar: "شموخ", en: "Shumoukh", gender: "f", meanAr: "العلو والأنفة", meanEn: "Pride, loftiness" },
  { ar: "ندى", en: "Nada", gender: "f", meanAr: "الندى والسخيّة", meanEn: "Dew; generosity" },
  { ar: "أريج", en: "Areej", gender: "f", meanAr: "رائحة الطيب", meanEn: "Fragrance" },
  { ar: "ريم", en: "Reem", gender: "f", meanAr: "الظبية البيضاء", meanEn: "White gazelle" },
  { ar: "لينا", en: "Lina", gender: "f", meanAr: "اللينة الرقيقة", meanEn: "Tender, palm tree" },
  { ar: "يارا", en: "Yara", gender: "f", meanAr: "الحبيبة الصغيرة / اسم آرامي أصيل", meanEn: "Beloved; a small butterfly" },
  { ar: "غلا", en: "Ghala", gender: "f", meanAr: "الغالية العزيزة", meanEn: "Precious, dear" },
  { ar: "عبير", en: "Abeer", gender: "f", meanAr: "عبير الطيب", meanEn: "Scent, perfume" },
  { ar: "هيفاء", en: "Haifa", gender: "f", meanAr: "الرشيقة الدقيقة الخصر", meanEn: "Slender, graceful" },
  { ar: "أمل", en: "Amal", gender: "f", meanAr: "الرجاء والأمل", meanEn: "Hope" },
  { ar: "إيمان", en: "Iman", gender: "f", meanAr: "التصديق والإيمان", meanEn: "Faith" },
  { ar: "أبرار", en: "Abrar", gender: "f", meanAr: "الصادقات البارّات", meanEn: "The righteous" },
  { ar: "هدى", en: "Huda", gender: "f", meanAr: "الرشد والهداية", meanEn: "Guidance" },
  { ar: "سلمى", en: "Salma", gender: "f", meanAr: "السالمة الآمنة", meanEn: "Safe, peaceful" },
  { ar: "ليلى", en: "Layla", gender: "f", meanAr: "الليل / الولادة ليلاً", meanEn: "Night" },
  { ar: "أسماء", en: "Asma", gender: "f", meanAr: "الرفيعة القدر", meanEn: "Exalted" },
  { ar: "زينب", en: "Zainab", gender: "f", meanAr: "شجرة حسنة المنظر", meanEn: "A fragrant tree" },
  { ar: "رقية", en: "Ruqayyah", gender: "f", meanAr: "التي ترتقي / ابنة النبي", meanEn: "To rise; the Prophet’s daughter" },
  { ar: "جمانة", en: "Jumana", gender: "f", meanAr: "اللؤلؤة", meanEn: "Pearl" },
  { ar: "لطيفة", en: "Latifah", gender: "f", meanAr: "الرقيقة اللطيفة", meanEn: "Kind, gentle" },
  { ar: "هيا", en: "Haya", gender: "f", meanAr: "الاسم النجدى الأصيل", meanEn: "A classic Najdi name" },
  { ar: "سدين", en: "Sadeen", gender: "f", meanAr: "غطاء الكعبة / الستر الرفيع", meanEn: "The Kaaba’s covering" },
  { ar: "مها", en: "Maha", gender: "f", meanAr: "بقرة الوحش — سعة العين", meanEn: "Oryx; wide-eyed" },
  { ar: "نجلاء", en: "Najla", gender: "f", meanAr: "واسعة العينين", meanEn: "Wide-eyed" },
  { ar: "وعد", en: "Waad", gender: "u", meanAr: "العهد والوعد", meanEn: "Promise" },
  { ar: "نور", en: "Noor", gender: "u", meanAr: "الضياء", meanEn: "Light" },
  { ar: "إياد", en: "Eyad", gender: "m", meanAr: "القوة والحصن", meanEn: "Strength, fortress" },
  { ar: "تميم", en: "Tamim", gender: "m", meanAr: "التام الكامل", meanEn: "Complete, perfect" },
  { ar: "غنام", en: "Ghannam", gender: "m", meanAr: "صاحب الغنم / الكثير الخير", meanEn: "Shepherd; abundant" },
  { ar: "هتان", en: "Hattan", gender: "m", meanAr: "المطر المتتابع", meanEn: "Steady rain" },
];

export function searchNames(q: string, gender: "all" | "m" | "f") {
  const n = q.trim().toLowerCase();
  return NAMES.filter((x) => {
    if (gender !== "all" && x.gender !== gender && x.gender !== "u") return false;
    if (!n) return true;
    return x.ar.includes(q.trim()) || x.en.toLowerCase().includes(n);
  });
}
