import type { SeedPost } from "./types.ts";

/**
 * Always-on local seed. Loaded from code for every new visitor — never from an
 * empty server. Official house posts are unmarked as samples; community posts
 * carry `sample-*` authors and are stamped in the UI as starter samples.
 */
export const SEED_POSTS: SeedPost[] = [
  {
    id: "seed-01",
    authorId: "house-waha",
    kind: "text",
    textAr: "أهلاً بك في الميدان. هنا يمرّ الكلام الهادئ، بلا ضجيج. البذرة هنا حتى لا تفتح على فراغ.",
    textEn: "Welcome to the Square. Quiet speech passes here. The seed is here so you never open onto emptiness.",
    ageMinutes: 4,
    likes: 28,
    echoes: 6,
    replies: [
      {
        id: "seed-01-r1",
        authorId: "sample-noura",
        textAr: "الميدان أحسن من الفراغ. شكراً.",
        textEn: "The Square is better than emptiness. Thank you.",
        ageMinutes: 2,
      },
    ],
  },
  {
    id: "seed-02",
    authorId: "house-tahajjud",
    kind: "text",
    textAr: "فائدة صلاة: ركعتان قبل أن يبرد الوضوء أهون من عشر نيّات مؤجّلة.",
    textEn: "A prayer note: two rak‘ahs before wudu cools are lighter than ten postponed intentions.",
    ageMinutes: 7,
    likes: 41,
    echoes: 11,
    replies: [
      {
        id: "seed-02-r1",
        authorId: "sample-salem",
        textAr: "هذه ذكرتني ألا أؤجّل الوضوء.",
        textEn: "This reminded me not to delay wudu.",
        ageMinutes: 3,
      },
    ],
  },
  {
    id: "seed-03",
    authorId: "sample-salem",
    kind: "text",
    textAr: "أنهيت حزباً وأنا في الانتظار. أحسن من التمرير بلا وعي.",
    textEn: "I finished a hizb while waiting. Better than scrolling without noticing.",
    ageMinutes: 12,
    likes: 9,
    echoes: 1,
  },
  {
    id: "seed-04",
    authorId: "house-waha",
    kind: "door",
    textAr: "الميدان للناس، والآبار للخدمة. إن احتجت صلاة أو أداة فالباب أقرب مما تظن.",
    textEn: "The Square is for people; the wells are for service. If you need a prayer time or a tool, the door is nearer than you think.",
    door: "madar",
    ageMinutes: 18,
    likes: 19,
    echoes: 4,
  },
  {
    id: "seed-05",
    authorId: "sample-noura",
    kind: "media",
    textAr: "القهوة الأولى بلا شاشة. جرّبوها مرة.",
    textEn: "The first coffee without a screen. Try it once.",
    media: "night",
    ageMinutes: 25,
    likes: 17,
    echoes: 3,
  },
  {
    id: "seed-06",
    authorId: "house-midad",
    kind: "text",
    textAr: "فكرة قراءة: صفحة واحدة بعد العشاء أضمن من ختمة تُؤجَّل كل رمضان.",
    textEn: "A reading idea: one page after Isha is surer than a khatma postponed every Ramadan.",
    ageMinutes: 38,
    likes: 33,
    echoes: 8,
    replies: [
      {
        id: "seed-06-r1",
        authorId: "sample-huda",
        textAr: "صفحة بعد العشاء صارت عادتي.",
        textEn: "A page after Isha became my habit.",
        ageMinutes: 20,
      },
    ],
  },
  {
    id: "seed-07",
    authorId: "sample-fahd",
    kind: "text",
    textAr: "أداة الوقود وفّرت عليّ جدال «كم نحتاج بنزين للطريق».",
    textEn: "The fuel tool spared me the argument of “how much petrol for the road”.",
    ageMinutes: 52,
    likes: 8,
    echoes: 0,
  },
  {
    id: "seed-08",
    authorId: "house-tahajjud",
    kind: "door",
    textAr: "إن فاتتك جماعة، لا تُفْت نفسك. صلِّ حيث أنت، ثم امشِ.",
    textEn: "If you miss the congregation, do not undo yourself. Pray where you are, then walk.",
    door: "tahajjud",
    ageMinutes: 67,
    likes: 36,
    echoes: 9,
  },
  {
    id: "seed-09",
    authorId: "sample-hind",
    kind: "text",
    textAr: "الأطفال حفظوا حرف الجيم اليوم. باب الحروف في الواحة لطيف للصغار.",
    textEn: "The children learned the letter jeem today. The letters door in Waha is gentle for little ones.",
    ageMinutes: 85,
    likes: 14,
    echoes: 2,
  },
  {
    id: "seed-10",
    authorId: "house-mohsin",
    kind: "text",
    textAr: "الإحسان أحياناً كوب ماء لمن بجانبك قبل أن تسأل كيف تساعد العالم.",
    textEn: "Ihsan is sometimes a glass of water for the person beside you, before you ask how to help the world.",
    ageMinutes: 110,
    likes: 44,
    echoes: 12,
  },
  {
    id: "seed-11",
    authorId: "house-luma",
    kind: "text",
    textAr: "لعبة قصيرة: كلمة واحدة، ست محاولات. استراحة لا تسرق الليل.",
    textEn: "A short game: one word, six tries. A pause that does not steal the night.",
    ageMinutes: 140,
    likes: 21,
    echoes: 5,
  },
  {
    id: "seed-12",
    authorId: "house-midad",
    kind: "quote",
    textAr: "والمهد هنا: خمس دقائق قبل النوم.",
    textEn: "And the cradle, here, is five minutes before sleep.",
    quoteAr: "اطلبوا العلم من المهد إلى اللحد",
    quoteEn: "Seek knowledge from the cradle to the grave",
    quoteAttrAr: "أثر مشهور",
    quoteAttrEn: "A well-known saying",
    media: "ink",
    ageMinutes: 180,
    likes: 29,
    echoes: 7,
  },
  {
    id: "seed-13",
    authorId: "sample-yasir",
    kind: "text",
    textAr: "نمت على دورة تسعين دقيقة، وصحوت أخف مما أعتاد.",
    textEn: "I slept on a ninety-minute cycle and woke lighter than usual.",
    ageMinutes: 210,
    likes: 11,
    echoes: 1,
  },
  {
    id: "seed-14",
    authorId: "house-tools",
    kind: "text",
    textAr: "الطقس قبل أن تخرج: حرّ الظهيرة في نجد لا يُجادَل. دقيقة واحدة تكفي.",
    textEn: "Weather before you step out: midday heat in Najd is not a debate. One minute is enough.",
    ageMinutes: 240,
    likes: 16,
    echoes: 2,
  },
  {
    id: "seed-15",
    authorId: "sample-maryam",
    kind: "quote",
    textAr: "وأنا أتعلّم أن أكتفي بما في اليد.",
    textEn: "And I am learning to be content with what is in hand.",
    quoteAr: "القناعة كنز لا يفنى",
    quoteEn: "Contentment is a treasure that does not perish",
    quoteAttrAr: "مثل عربي",
    quoteAttrEn: "Arabic proverb",
    ageMinutes: 280,
    likes: 18,
    echoes: 4,
  },
  {
    id: "seed-16",
    authorId: "house-waha",
    kind: "text",
    textAr: "تُحفظ كتابتك على هذا الجهاز. لا خادم فارغ ينتظر — ابدأ سطراً إن شئت.",
    textEn: "Your writing is saved on this device. No empty server is waiting — begin a line if you wish.",
    ageMinutes: 320,
    likes: 22,
    echoes: 3,
  },
  {
    id: "seed-17",
    authorId: "sample-khalid",
    kind: "door",
    textAr: "فتحت مدار بعد صلاة العصر. حسّ أن البيت قريب.",
    textEn: "I opened Madar after Asr. It felt like the house was near.",
    door: "madar",
    ageMinutes: 360,
    likes: 7,
    echoes: 1,
  },
  {
    id: "seed-18",
    authorId: "house-tahajjud",
    kind: "text",
    textAr: "أذكار الصباح لا تحتاج تطبيقاً فخماً — تحتاج دقيقة صادقة. افتح الورد إن أحببت.",
    textEn: "Morning athkar do not need a grand app — they need an honest minute. Open the wird if you like.",
    ageMinutes: 420,
    likes: 31,
    echoes: 6,
  },
  {
    id: "seed-19",
    authorId: "sample-layla",
    kind: "media",
    textAr: "الطقس اليوم لطف بعد أمس. مشيت إلى المسجد على مهل.",
    textEn: "The weather eased after yesterday. I walked to the mosque slowly.",
    media: "dune",
    ageMinutes: 480,
    likes: 13,
    echoes: 2,
  },
  {
    id: "seed-20",
    authorId: "house-midad",
    kind: "door",
    textAr: "اقرأ ولو آية. الباب مفتوح، والختمة لا تُقاس بالسرعة.",
    textEn: "Read even one ayah. The door is open, and a khatma is not measured by speed.",
    door: "midad",
    ageMinutes: 540,
    likes: 27,
    echoes: 5,
  },
  {
    id: "seed-21",
    authorId: "sample-omar",
    kind: "text",
    textAr: "بلوت مع الوالد. هو فاز، وأنا ربحت الجلسة.",
    textEn: "Baloot with my father. He won; I gained the sitting.",
    ageMinutes: 600,
    likes: 20,
    echoes: 3,
  },
  {
    id: "seed-22",
    authorId: "house-mohsin",
    kind: "text",
    textAr: "الزكاة حساب واضح، والنية أسبق من الرقم. إن أحببت، الحاسبة هادئة في مالِك.",
    textEn: "Zakat is a clear sum, and the intention precedes the number. The calculator, if you want it, is quiet in Money.",
    ageMinutes: 680,
    likes: 24,
    echoes: 4,
  },
  {
    id: "seed-23",
    authorId: "sample-sara",
    kind: "text",
    textAr: "حسبت الزكاة بعد سنين تأجيل. أهون مما تصوّرت.",
    textEn: "I calculated zakat after years of putting it off. Lighter than I had pictured.",
    ageMinutes: 760,
    likes: 15,
    echoes: 2,
  },
  {
    id: "seed-24",
    authorId: "house-tools",
    kind: "text",
    textAr: "حوّل الوحدات قبل أن تشتري. القياس أصدق من التخمين.",
    textEn: "Convert the units before you buy. Measure is truer than a guess.",
    ageMinutes: 840,
    likes: 10,
    echoes: 1,
  },
  {
    id: "seed-25",
    authorId: "sample-badr",
    kind: "quote",
    textAr: "جدّي كان يقولها وأنا أرتّب مكتبي كل خميس.",
    textEn: "My grandfather used to say it, and I tidy my desk every Thursday.",
    quoteAr: "من جدّ وجد",
    quoteEn: "Whoever strives, finds",
    quoteAttrAr: "مثل عربي",
    quoteAttrEn: "Arabic proverb",
    ageMinutes: 920,
    likes: 12,
    echoes: 2,
  },
  {
    id: "seed-26",
    authorId: "house-luma",
    kind: "text",
    textAr: "إن ضاق الصدر: أربع شهيق، سبع حبس، ثماني زفير. دقيقة واحدة في باب التنفس.",
    textEn: "If the chest tightens: in for four, hold for seven, out for eight. One minute in Breathe.",
    ageMinutes: 1000,
    likes: 26,
    echoes: 8,
  },
  {
    id: "seed-27",
    authorId: "sample-amal",
    kind: "text",
    textAr: "كتبت قائمة التسوق قبل السوق. رجعت بلا ندم.",
    textEn: "I wrote the shopping list before the souq. I came back without regret.",
    ageMinutes: 1100,
    likes: 9,
    echoes: 0,
  },
  {
    id: "seed-28",
    authorId: "house-tahajjud",
    kind: "text",
    textAr: "القبلة ثابتة، والقلب يتلفّت. دقيقة اتجاه تكفي لتعود.",
    textEn: "The qibla is fixed; the heart turns about. A minute of bearing is enough to return.",
    ageMinutes: 1200,
    likes: 30,
    echoes: 6,
  },
  {
    id: "seed-29",
    authorId: "sample-talal",
    kind: "text",
    textAr: "تجربة التنفس قبل اجتماع. فرق واضح في الصوت.",
    textEn: "Tried the breathing exercise before a meeting. A clear difference in the voice.",
    ageMinutes: 1320,
    likes: 8,
    echoes: 1,
  },
  {
    id: "seed-30",
    authorId: "house-midad",
    kind: "text",
    textAr: "اسم من أسمائه يكفي لتليين اليوم. افتح الأسماء الحسنى إن شئت.",
    textEn: "One of His names is enough to soften the day. Open the Ninety-Nine if you wish.",
    ageMinutes: 1440,
    likes: 34,
    echoes: 7,
  },
  {
    id: "seed-31",
    authorId: "sample-huda",
    kind: "text",
    textAr: "ختمة بطيئة خير من نية سريعة. جزء في الأسبوع يكفيني الآن.",
    textEn: "A slow khatma is better than a swift intention. One juz a week is enough for me now.",
    ageMinutes: 1560,
    likes: 16,
    echoes: 3,
  },
  {
    id: "seed-32",
    authorId: "house-tools",
    kind: "text",
    textAr: "عجلة القرار إذا تحيّرت بين أمرين مباحين — لا بين حق وباطل.",
    textEn: "The decision wheel is for when you hesitate between two permissible things — not between right and wrong.",
    ageMinutes: 1680,
    likes: 19,
    echoes: 4,
  },
  {
    id: "seed-33",
    authorId: "sample-majed",
    kind: "text",
    textAr: "راجعت رخصة السيارة من «سيارتي». كانت أقرب مما أظن.",
    textEn: "I checked the car license in My car. It was nearer than I thought.",
    ageMinutes: 1800,
    likes: 7,
    echoes: 0,
  },
  {
    id: "seed-34",
    authorId: "house-mohsin",
    kind: "text",
    textAr: "اتصل بوالدك اليوم — لا تحتاج مناسبة. المناسبة أنك قادر.",
    textEn: "Call your father today — you do not need an occasion. The occasion is that you can.",
    ageMinutes: 1920,
    likes: 48,
    echoes: 14,
  },
  {
    id: "seed-35",
    authorId: "sample-reem",
    kind: "text",
    textAr: "لعبة الذاكرة مع ابن أخي. الضحك أكثر من النقاط.",
    textEn: "Memory with my nephew. More laughter than points.",
    ageMinutes: 2100,
    likes: 11,
    echoes: 1,
  },
  {
    id: "seed-36",
    authorId: "house-waha",
    kind: "text",
    textAr: "هوية الواحة: عربي، من اليمين، وهدوء. ليست ساحة تتشبّه بغيرها؛ هي ميدان بيت.",
    textEn: "Waha’s voice: Arabic, from the right, and quiet. Not a square that copies another; it is a house courtyard.",
    ageMinutes: 2280,
    likes: 25,
    echoes: 5,
  },
  {
    id: "seed-37",
    authorId: "sample-walid",
    kind: "text",
    textAr: "حوّلت المبلغ لتفقيط الفاتورة. سلّمت بلا لخبطة أرقام.",
    textEn: "I turned the amount into words for the invoice. Handed it over without mixed-up numbers.",
    ageMinutes: 2460,
    likes: 6,
    echoes: 0,
  },
  {
    id: "seed-38",
    authorId: "house-luma",
    kind: "text",
    textAr: "البلوت للجلسة، والتنفّس للوحدة. اختر ما يُصلح هذه الساعة لا ما يملأها.",
    textEn: "Baloot for company, breathing for solitude. Choose what mends this hour, not what fills it.",
    ageMinutes: 2640,
    likes: 18,
    echoes: 3,
  },
  {
    id: "seed-39",
    authorId: "sample-jawaher",
    kind: "media",
    textAr: "صباح هادئ: آية الكرسي، ثم العمل. هذا نظمي هذه الأيام.",
    textEn: "A quiet morning: Ayat al-Kursi, then work. That is my order these days.",
    media: "palm",
    ageMinutes: 2820,
    likes: 22,
    echoes: 4,
  },
  {
    id: "seed-40",
    authorId: "house-tahajjud",
    kind: "text",
    textAr: "بين الأذان والإقامة متسع لدعاء قصير. لا تملأه بالشاشة.",
    textEn: "Between adhan and iqama there is room for a short dua. Do not fill it with the screen.",
    ageMinutes: 3000,
    likes: 39,
    echoes: 10,
  },
  {
    id: "seed-41",
    authorId: "sample-anas",
    kind: "text",
    textAr: "جرّبت القبلة من الغرفة. زاويتي كانت مائلة قليلاً.",
    textEn: "I tried the qibla from the room. My corner was a little off.",
    ageMinutes: 3240,
    likes: 9,
    echoes: 1,
  },
  {
    id: "seed-42",
    authorId: "house-midad",
    kind: "text",
    textAr: "الكتاب الذي لا تلمسه يضعف. المس المصحف أو الورد — المهم أن تعود.",
    textEn: "A book you do not touch grows weak. Touch the mushaf or the wird — the point is that you return.",
    ageMinutes: 3480,
    likes: 28,
    echoes: 6,
  },
  {
    id: "seed-43",
    authorId: "sample-lina",
    kind: "quote",
    textAr: "أعلّقها فوق المكتب حتى أذكر أن الأمنية بلا عمل تذبل.",
    textEn: "I pin it above the desk so I remember that a wish without work withers.",
    quoteAr: "إذا تمنيت فاعمل",
    quoteEn: "If you wish, then work",
    quoteAttrAr: "حكمة دارجة",
    quoteAttrEn: "A spoken wisdom",
    ageMinutes: 3720,
    likes: 14,
    echoes: 2,
  },
  {
    id: "seed-44",
    authorId: "house-tools",
    kind: "text",
    textAr: "آيبان تتحقق منه قبل التحويل. دقيقة تقي أسبوع اعتذار.",
    textEn: "Check an IBAN before you transfer. A minute saves a week of apology.",
    ageMinutes: 3960,
    likes: 13,
    echoes: 2,
  },
  {
    id: "seed-45",
    authorId: "house-mohsin",
    kind: "media",
    textAr: "قائمة البيت إن كُتبت خفّت. المحسن يبدأ من بابه لا من الشعار.",
    textEn: "A household list, once written, grows lighter. The muhsin starts at his door, not at a slogan.",
    media: "mist",
    ageMinutes: 4200,
    likes: 21,
    echoes: 3,
  },
  {
    id: "seed-46",
    authorId: "house-luma",
    kind: "text",
    textAr: "واحة للذكاء إن احتجت صياغة رسالة أو ترجمة سطر — بلا ادعاء، وبلا إطالة.",
    textEn: "Waha AI if you need a letter drafted or a line translated — without pretence, and without length.",
    ageMinutes: 4440,
    likes: 17,
    echoes: 2,
  },
];

export const MIN_SEED_POSTS = 40;
