/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LifeRouteImport } from './routes/life'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as AskRouteImport } from './routes/ask'
import { Route as HouseRouteImport } from './routes/house'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppIdRouteImport } from './routes/app.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeRoute = LifeRouteImport.update({
  id: '/life',
  path: '/life',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdRoute = AppIdRouteImport.update({
  id: '/app/$id',
  path: '/app/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/life': typeof LifeRoute
  '/money': typeof MoneyRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/workspace': typeof WorkspaceRoute
  '/ask': typeof AskRoute
  '/house': typeof HouseRoute
  '/settings': typeof SettingsRoute
  '/labs': typeof LabsRoute
  '/admin': typeof AdminRoute
  '/app/$id': typeof AppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/life': typeof LifeRoute
  '/money': typeof MoneyRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/workspace': typeof WorkspaceRoute
  '/ask': typeof AskRoute
  '/house': typeof HouseRoute
  '/settings': typeof SettingsRoute
  '/labs': typeof LabsRoute
  '/admin': typeof AdminRoute
  '/app/$id': typeof AppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/life': typeof LifeRoute
  '/money': typeof MoneyRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/workspace': typeof WorkspaceRoute
  '/ask': typeof AskRoute
  '/house': typeof HouseRoute
  '/settings': typeof SettingsRoute
  '/labs': typeof LabsRoute
  '/admin': typeof AdminRoute
  '/app/$id': typeof AppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/life'
    | '/money'
    | '/studio'
    | '/tools'
    | '/workspace'
    | '/ask'
    | '/house'
    | '/settings'
    | '/labs'
    | '/admin'
    | '/app/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games'
    | '/life'
    | '/money'
    | '/studio'
    | '/tools'
    | '/workspace'
    | '/ask'
    | '/house'
    | '/settings'
    | '/labs'
    | '/admin'
    | '/app/$id'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/life'
    | '/money'
    | '/studio'
    | '/tools'
    | '/workspace'
    | '/ask'
    | '/house'
    | '/settings'
    | '/labs'
    | '/admin'
    | '/app/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRoute
  LifeRoute: typeof LifeRoute
  MoneyRoute: typeof MoneyRoute
  StudioRoute: typeof StudioRoute
  ToolsRoute: typeof ToolsRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AskRoute: typeof AskRoute
  HouseRoute: typeof HouseRoute
  SettingsRoute: typeof SettingsRoute
  LabsRoute: typeof LabsRoute
  AdminRoute: typeof AdminRoute
  AppIdRoute: typeof AppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life': {
      id: '/life'
      path: '/life'
      fullPath: '/life'
      preLoaderRoute: typeof LifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id': {
      id: '/app/$id'
      path: '/app/$id'
      fullPath: '/app/$id'
      preLoaderRoute: typeof AppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRoute,
  LifeRoute: LifeRoute,
  MoneyRoute: MoneyRoute,
  StudioRoute: StudioRoute,
  ToolsRoute: ToolsRoute,
  WorkspaceRoute: WorkspaceRoute,
  AskRoute: AskRoute,
  HouseRoute: HouseRoute,
  SettingsRoute: SettingsRoute,
  LabsRoute: LabsRoute,
  AdminRoute: AdminRoute,
  AppIdRoute: AppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
